# k8s/worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-malware-worker
  namespace: check-malware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-malware-worker
  template:
    metadata:
      labels:
        app: check-malware-worker
    spec:
      containers:
      - name: worker
        image: your-registry/check-malware-worker:latest
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "check_malware", "worker", "--loglevel=info", "--concurrency=1"]
        envFrom:
        - configMapRef:
            name: check-malware-config
        - secretRef:
            name: check-malware-secrets
        env:
        - name: CLAMAV_HOST
          valueFrom:
            configMapKeyRef:
              name: check-malware-config
              key: CLAMAV_HOST
        - name: CLAMAV_PORT
          valueFrom:
            configMapKeyRef:
              name: check-malware-config
              key: CLAMAV_PORT
        volumeMounts:
        - name: media
          mountPath: /app/media
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
